//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.WordFilter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordFilter.IWordFilterService")]
    public interface IWordFilterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordFilterService/WordFilter", ReplyAction="http://tempuri.org/IWordFilterService/WordFilterResponse")]
        string WordFilter(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordFilterService/WordFilter", ReplyAction="http://tempuri.org/IWordFilterService/WordFilterResponse")]
        System.Threading.Tasks.Task<string> WordFilterAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordFilterServiceChannel : WebApplication.WordFilter.IWordFilterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordFilterServiceClient : System.ServiceModel.ClientBase<WebApplication.WordFilter.IWordFilterService>, WebApplication.WordFilter.IWordFilterService {
        
        public WordFilterServiceClient() {
        }
        
        public WordFilterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordFilterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordFilterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordFilterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WordFilter(string str) {
            return base.Channel.WordFilter(str);
        }
        
        public System.Threading.Tasks.Task<string> WordFilterAsync(string str) {
            return base.Channel.WordFilterAsync(str);
        }
    }
}
